language: python

matrix:
    include:
        - python: 3.4
          os: linux
          dist: trusty
          env: TOXENV=flake8
        - python: 2.7
          os: linux
          dist: trusty
          env: TOXENV=py27
        - python: 3.4
          os: linux
          dist: trusty
          env: TOXENV=py34
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36
        - python: 3.7
          os: linux
          dist: xenial
          env: TOXENV=py37

install:
  - pip install tox

script:
  - tox -e "${TOXENV}"
